package runtime

import (
	"fmt"
	"os"
)

// GeneratedHeader is the canonical comment block prepended to a generated
// functions YAML file. Identifies the file as auto-generated, documents the
// regenerate + drift-guard commands, and explains the load-order contract
// (underscore prefix forces lex-first load so the manual schema overlay
// declared in the same directory can override any field via the
// merge-on-duplicate policy in declarion-core's Registry).
const GeneratedHeader = `# Code generated by cmd/gen-functions-yaml. DO NOT EDIT.
# Regenerate via: make gen-functions-yaml
# Drift guard: make verify-functions-yaml
#
# Coverage: every function registered via sdk.RegisterFunction across the
# packages blank-imported in cmd/gen-functions-yaml/main.go.
#
# This file is loaded BEFORE the manual declarion/schema/actions.yaml — the
# underscore prefix forces lex-first load order. The manual file may override
# any field declared here via the merge-on-duplicate policy implemented in
# declarion-core's Registry.AddHandler / Registry.AddAction.
`

// RunGenerator is the canonical entry point for a derivative project's
// cmd/gen-functions-yaml binary. It writes GeneratedHeader followed by the
// output of GenerateFunctionsYAML to stdout, exiting non-zero on any error.
//
// Consumers should keep cmd/gen-functions-yaml/main.go as a literal one-liner:
//
//	package main
//
//	import (
//	    sdk "github.com/disciplinedware/declarion-sdk-go/runtime"
//	    _ "github.com/your-org/your-project/internal/handlers/all" // blank-imports
//	)
//
//	func main() { sdk.RunGenerator() }
//
// The blank-import list IS the project's contribution; everything else is
// owned by the SDK. See examples/gen-functions-yaml/main.go for the canonical
// template.
func RunGenerator() {
	if _, err := fmt.Fprint(os.Stdout, GeneratedHeader); err != nil {
		fmt.Fprintf(os.Stderr, "gen-functions-yaml: write header: %v\n", err)
		os.Exit(1)
	}
	if err := GenerateFunctionsYAML(os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "gen-functions-yaml: %v\n", err)
		os.Exit(1)
	}
}
