package runtime

import (
	"fmt"
	"os"
)

// GeneratedHeader is the canonical comment block prepended to a generated
// functions YAML file.
const GeneratedHeader = `# Code generated by cmd/gen-functions-yaml. DO NOT EDIT.
# Regenerate via: make gen-functions-yaml
# Drift guard: make verify-functions-yaml
#
# Coverage: every handler registered via sdk.RegisterHandler across the
# packages blank-imported in cmd/gen-functions-yaml/main.go.
#
# This file is loaded BEFORE the manual schema overlay. The generated file is a
# thin JSON-RPC stub only: handler code, transport URL, and params reflected
# from Go. Actions, display, permissions, timeout, retry, webhook security, and
# other configuration belong in hand-written YAML loaded after this file.
`

// Generate is the canonical entry point for a derivative project's
// cmd/gen-functions-yaml binary. It writes GeneratedHeader followed by the
// output of GenerateFunctionsYAML to stdout, exiting non-zero on any error.
func Generate() {
	if _, err := fmt.Fprint(os.Stdout, GeneratedHeader); err != nil {
		fmt.Fprintf(os.Stderr, "gen-functions-yaml: write header: %v\n", err)
		os.Exit(1)
	}
	if err := GenerateFunctionsYAML(os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "gen-functions-yaml: %v\n", err)
		os.Exit(1)
	}
}
